apps/chat/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import ChatIndexPage


urlpatterns = [
    url(r'^$', login_required(ChatIndexPage.as_view()), name='index')
]

apps/private_messages/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import PrivateMessageTemplateView, PrivateMessageCreateView


urlpatterns = [
    url(r'^$', login_required(PrivateMessageTemplateView.as_view()),
        name='index'),
    url(r'^(?P<recipient>\d+)/$',
        login_required(PrivateMessageCreateView.as_view()),
        name='private')
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import login, logout

from apps.main.views import RegistrationView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', login, name='login'),
    url(r'^registration/', RegistrationView.as_view(), name='registration'),
    url(r'^logout/', logout, name='logout'),
    url(r'^chat/', include('apps.chat.urls', namespace='chat')),
    url(r'^private/', include('apps.private_messages.urls',
                              namespace='private_messages')),
]

urlpatterns += static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/chat/models.py
import json
from channels import Group
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models


class ChatUserManager(BaseUserManager):
    def create_user(self, email=None, password=None, user_role=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            user_role=user_role,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email=email,
            password=password,
        )
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class ChatUser(PermissionsMixin, AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', unique=True)
    first_name = models.CharField(verbose_name="Имя", max_length=255)
    last_name = models.CharField(verbose_name="Фамилия", max_length=255)

    is_active = models.BooleanField(
        verbose_name="Активность",
        default=True,
        null=False
    )
    is_staff = models.BooleanField(default=False, null=False)

    objects = ChatUserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"


class ChatMessage(models.Model):
    message = models.TextField(verbose_name="message")
    created = models.DateTimeField(verbose_name="created", auto_now_add=True)
    user = models.ForeignKey(ChatUser)

    @property
    def author(self):
        return "{} {}".format(self.user.first_name, self.user.last_name)

    def send_to_chat(self, chat_name):
        Group(chat_name).send({
            "text": json.dumps({
                "created": self.created.strftime("%H:%M "),
                "message": self.message,
                "username": self.author,
            })
        })

    class Meta:
        ordering = ['created']
        verbose_name = "Chat message"
        verbose_name_plural = "Chat messages"

apps/private_messages/models.py
from django.db import models


class PrivateMessage(models.Model):
    owner = models.ForeignKey(to='chat.ChatUser')
    recipient = models.ForeignKey(to='chat.ChatUser', related_name='rec')
    message = models.TextField(verbose_name="message")
    created = models.DateTimeField(verbose_name="created", auto_now_add=True)

    @property
    def author(self):
        return "{} {}".format(self.owner.first_name, self.owner.last_name)

    class Meta:
        ordering = ['created']
        verbose_name = "Private messages"
        verbose_name_plural = "Private messages"

apps/chat/views.py
from django.views.generic import ListView

from apps.main.views.mixins import AdminPageViewMixin
from .models import ChatMessage


class ChatIndexPage(AdminPageViewMixin, ListView):
    template_name = 'chat/index.html'
    model = ChatMessage

apps/main/views/registration.py
from django import forms
from django.contrib.auth import authenticate, login
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import CreateView

from apps.chat.models import ChatUser
from .mixins import AdminPageViewMixin


class UsersForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True

    class Meta:
        model = ChatUser
        fields = ('email', 'first_name', 'last_name', 'password')
        labels = {
            "email": "Email"
        }


class RegistrationView(AdminPageViewMixin, CreateView):
    model = ChatUser
    form_class = UsersForm
    template_name = 'registration/registration.html'

    def get_success_url(self):
        return reverse('chat:index')

    def form_valid(self, form):
        instance = form.save(commit=False)
        email, password = instance.email, instance.password
        instance.set_password(instance.password)
        instance.save()

        user = authenticate(email=email, password=password)
        login(self.request, user)

        return HttpResponseRedirect(self.get_success_url())

apps/private_messages/views.py
from django.db.models import Q
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, TemplateView

from apps.chat.models import ChatUser
from apps.main.views.mixins import AdminPageViewMixin
from .models import PrivateMessage


class PrivateMessageTemplateView(AdminPageViewMixin, TemplateView):
    template_name = 'private_messages/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_list = ChatUser.objects.all().exclude(is_superuser=True)

        context['user_list'] = [
            {
                "user": user,
                "messages_count": PrivateMessage.objects.filter(
                    Q(owner=self.request.user) | Q(recipient=user)).count()
            }
            for user in user_list
        ]
        return context


class PrivateMessageCreateView(AdminPageViewMixin, CreateView):
    model = PrivateMessage
    fields = ('message',)
    template_name = 'private_messages/private.html'

    def get_success_url(self):
        return reverse("private_messages:private",
                       kwargs={"recipient": self.recipient.pk})

    def dispatch(self, request, *args, **kwargs):
        recipient_pk = kwargs.get('recipient', 0)
        self.recipient = get_object_or_404(ChatUser, pk=recipient_pk)
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owner = self.request.user
        instance.recipient = self.recipient
        instance.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['recipient'] = self.recipient
        context['message_list'] = PrivateMessage.objects.filter(
            (Q(owner=self.request.user) and Q(recipient=self.recipient)) |
            (Q(owner=self.recipient) and Q(recipient=self.request.user))
        )
        return context

apps/chat/templates/chat/index.html
{% extends "base.html" %}



{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'chat:index' %}">Групповой чат</a>
</div>
{% endblock %}



{% block content %}
{% block content_title %}{% endblock %}

    <script>
        var $ = django.jQuery;

        $(function () {
            $(document).ready(function() {
                function scrollBottom() {
                    $("html, body").animate({ scrollTop: $(document).height()-$(window).height()  }, "slow");
                }

                scrollBottom();
                var messageTable = $('#messages'),
                    messageForm = $('#message-form');
                socket = new WebSocket("ws://" + window.location.host + "/chat/stream/");
                socket.onmessage = function(e) {
                    var data = JSON.parse(e.data);
                    var messageRow = $(
                            "<li>" +
                                "<span><b>" + data.username + "</b> " + data.created + "</span>" +
                                "<p>" + data.message + "</p>" +
                            "</li>"
                    );
                    messageTable.append(messageRow);
                    scrollBottom();
                };

                messageForm.on("submit", function () {
                    socket.send(messageForm.find('textarea').val());
                    messageForm.find('textarea').val("");
                    return false;
                });
                socket.onopen = function () {
                    console.log("Connected to chat socket");
                };
                socket.onclose = function () {
                    console.log("Disconnected from chat socket");
                };
                if (socket.readyState == WebSocket.OPEN) socket.onopen();
            });
        });
    </script>
    <h1 style="text-align: center">Групповой чат</h1>
    <ul class="message-list" id="messages">
        {% for item in object_list %}
            <li>
                <span><b>{{ item.author }}</b> {{ item.created|time:"H:i" }}</span>
                <p>{{ item.message|safe }}</p>
            </li>
        {% endfor %}
    </ul>
    <br><br>
    <form id="message-form">
        <textarea></textarea>
        <input type="submit" value="Отправить">
    </form>

{% endblock %}

apps/main/templates/base.html
{% extends "admin/base_site.html" %}
{% load i18n admin_urls static admin_modify %}

{% block title %}{% endblock %}

{% block branding %}<h1>Лабораторная работа №6. XSS</h1>{% endblock %}

{% block extrahead %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'custom.css' %}">
    {{ admin_media }}
{% endblock %}



{% block usertools %}
    {% if request.user.is_authenticated %}
    <div id="user-tools">
        <span>Вы вошли как <b id="email">{{ request.user.email }}</b>. </span>
        {% block userlinks %}
            <a href="{% url 'private_messages:index' %}">Приватные сообщения</a> /
            <a href="{% url 'chat:index' %}"><b>Групповой чат</b></a> /
            <a href="{% url 'logout' %}">Выйти</a>
        {% endblock %}
    </div>
    {% endif %}
{% endblock %}


<div id="content-main">
{% block content %}

{% endblock %}
</div>

apps/private_messages/templates/private_messages/index.html
{% extends "base.html" %}



{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="{% url 'private_messages:index' %}">Все приватные сообщения</a>
</div>
{% endblock %}



{% block content %}
{% block content_title %}{% endblock %}
    <h1 style="text-align: center">Приватные сообщения. Выберите собеседника</h1>
    <p style="text-align: center">
        {% for item in user_list %}
            <span><a href="{% url 'private_messages:private' recipient=item.user.pk %}"><b>{{ item.user.first_name }} {{ item.user.last_name }}</b></a> ({{ item.messages_count }} сообщений)</span><br><br>
        {% endfor %}
    </p>
    <br><br>
{% endblock %}

apps/private_messages/templates/private_messages/private.html
{% extends "base.html" %}



{% block breadcrumbs %}
<div class="breadcrumbs">
    <a href="">Приватные сообщения</a>
</div>
{% endblock %}


{% block content %}
{% block content_title %}{% endblock %}
    <script>
        var $ = django.jQuery;
        $(function () {
            $(document).ready(function() {
                $("html, body").animate({ scrollTop: $(document).height()-$(window).height()  }, "slow");
            });
        });
    </script>

    <h1 style="text-align: center">Приватные сообщения c <b>{{ recipient.first_name }} {{ recipient.last_name }}</b></h1>
    <p style="text-align: center;" class="warning">Внимание, на данной странице не просиходит автоматического обновления содержания</p>
    <ul class="message-list" id="messages">
        {% for item in message_list %}
            <li>
                <span>
                    {{item.pk}}
                    {% ifequal request.user.pk item.owner.pk %}
                        <b>Вы</b>
                    {% else %}
                        <b>{{ item.author }}</b>
                    {% endifequal %}
                    {{ item.created|time:"H:i" }}
                </span>
                <p>{{ item.message }}</p>
            </li>
        {% endfor %}
    </ul>
    <br><br>
    <form id="message-form" method="POST" action=".">
        <textarea name="message" required></textarea>
        <input type="submit" value="Отправить">
    </form>
    <br><br>
{% endblock %}